spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://video-db:3306/videodb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: videouser
    password: videopass
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
